from django.conf.urls import url, include
from . import views
from . import shift
from . import privelige
from . import data_pasien
from . import pasien_rj
from . import master_produk
from . import kasir_rj
from . import daftar_paket
from . import paket_produk
from . import farmasi
from . import jasamedis001
from . import jasareseller001
from . import master_sumber


urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^cabang', views.cabang, name='cabang'),
    url(r'^shift/', include([
        url(r'^setShift', shift.setShift),
        url(r'^tutupShift', shift.tutupShift),
        url(r'^edit', shift.editShift),
        url(r'^updateShift', shift.updateShift),
        url(r'^getShiftList', shift.getShiftList),
        url(r'^getShift', shift.getShift),
    ])),
    url(r'^privilege/', include([
        url(r'^$', privelige.dashboard, name='privilege'),
        url(r'^menu/',privelige.menu, name='menu'),
        url(r'^menu_priv/',privelige.menu_priv, name='menu_priv'),
        url(r'^menu_post',privelige.menu_post, name='menu_post'),
        url(r'^user/',privelige.user, name='user'),

        url(r'^navbars/',privelige.navbars, name='navbars'),
        url(r'^navbars_priv/',privelige.navbars_priv, name='navbars_priv'),
        url(r'^navbars_post',privelige.navbars_post, name='navbars_post'),
        url(r'^subnavbars_priv/',privelige.subnavbars_priv, name='subnavbars_priv'),
        url(r'^subnavbars_post',privelige.subnavbars_post, name='subnavbars_post'),

        url(r'^menubars/',privelige.menubars, name='menubars'),
        url(r'^menubars_priv/',privelige.menubars_priv, name='menubars_priv'),
        url(r'^submenubars_priv/',privelige.submenubars_priv, name='submenubars_priv'),
        url(r'^menubars_post',privelige.menubars_post, name='menubars_post'),
        url(r'^submenubars_post',privelige.submenubars_post, name='submenubars_post'),


        ])
    ),
    url(r'^data_pasien/', include ([
        url(r'^$',data_pasien.data_pasien, name='data_pasien'),
        url(r'^getKelamin', data_pasien.getKelamin),
        url(r'^getDataKelamin', data_pasien.getDataKelamin),
        url(r'^getProvinsi', data_pasien.getProvinsi),
        url(r'^getDataProvinsi', data_pasien.getDataProvinsi),
        url(r'^getKabupaten', data_pasien.getKabupaten),
        url(r'^getDataKabupaten', data_pasien.getDataKabupaten),
        url(r'^getKecamatan', data_pasien.getKecamatan),
        url(r'^getDataKecamatan', data_pasien.getDataKecamatan),
        url(r'^getKelurahan', data_pasien.getKelurahan),
        url(r'^getDataKelurahan', data_pasien.getDataKelurahan),
        url(r'^getReseler', data_pasien.getReseler),
        url(r'^getDataReseler', data_pasien.getDataReseler),
        url(r'^getAgama', data_pasien.getAgama),
        url(r'^getDataAgama', data_pasien.getDataAgama),
        url(r'^getPendidikan', data_pasien.getPendidikan),
        url(r'^getDataPendidikan', data_pasien.getDataPendidikan),
        url(r'^getGoldarah', data_pasien.getGoldarah),
        url(r'^getDataGoldarah', data_pasien.getDataGoldarah),
        url(r'^getMarital', data_pasien.getMarital),
        url(r'^getDataMarital', data_pasien.getDataMarital),
        url(r'^getPekerjaan', data_pasien.getPekerjaan),
        url(r'^getDataPekerjaan', data_pasien.getDataPekerjaan),
        url(r'^getSuku', data_pasien.getSuku),
        url(r'^getDataSuku', data_pasien.getDataSuku),
        url(r'^getBahasa', data_pasien.getBahasa),
        url(r'^getDataBahasa', data_pasien.getDataBahasa),
        url(r'^getKlpPasien', data_pasien.getKlpPasien),
        url(r'^getDataKlpPasien', data_pasien.getDataKlpPasien),
        url(r'^getCustomer', data_pasien.getCustomer),
        url(r'^getDataCustomer', data_pasien.getDataCustomer),
        url(r'^getPasien', data_pasien.getPasien),
        url(r'^getDataPasien', data_pasien.getDataPasien),
        url(r'^GUD_PASIEN', data_pasien.GUD_PASIEN),

    ])),
    url(r'^pasien_rj/', include ([
        url(r'^$',pasien_rj.pasien_rj, name='pasien_rj'),
        url(r'^getKelamin', data_pasien.getKelamin),
        url(r'^getDataKelamin', data_pasien.getDataKelamin),
        url(r'^getProvinsi', data_pasien.getProvinsi),
        url(r'^getDataProvinsi', data_pasien.getDataProvinsi),
        url(r'^getKabupaten', data_pasien.getKabupaten),
        url(r'^getDataKabupaten', data_pasien.getDataKabupaten),
        url(r'^getKecamatan', data_pasien.getKecamatan),
        url(r'^getDataKecamatan', data_pasien.getDataKecamatan),
        url(r'^getKelurahan', data_pasien.getKelurahan),
        url(r'^getDataKelurahan', data_pasien.getDataKelurahan),
        url(r'^getReseler', data_pasien.getReseler),
        url(r'^getDataReseler', data_pasien.getDataReseler),
        url(r'^getAgama', data_pasien.getAgama),
        url(r'^getDataAgama', data_pasien.getDataAgama),
        url(r'^getPendidikan', data_pasien.getPendidikan),
        url(r'^getDataPendidikan', data_pasien.getDataPendidikan),
        url(r'^getGoldarah', data_pasien.getGoldarah),
        url(r'^getDataGoldarah', data_pasien.getDataGoldarah),
        url(r'^getMarital', data_pasien.getMarital),
        url(r'^getDataMarital', data_pasien.getDataMarital),
        url(r'^getPekerjaan', data_pasien.getPekerjaan),
        url(r'^getDataPekerjaan', data_pasien.getDataPekerjaan),
        url(r'^getSuku', data_pasien.getSuku),
        url(r'^getDataSuku', data_pasien.getDataSuku),
        url(r'^getBahasa', data_pasien.getBahasa),
        url(r'^getDataBahasa', data_pasien.getDataBahasa),
        url(r'^getKlpPasien', data_pasien.getKlpPasien),
        url(r'^getDataKlpPasien', data_pasien.getDataKlpPasien),
        url(r'^getCustomer', data_pasien.getCustomer),
        url(r'^getDataCustomer', data_pasien.getDataCustomer),
        url(r'^getPasien', data_pasien.getPasien),
        url(r'^getDataPasien', data_pasien.getDataPasien),
        url(r'^AUD_PASIENRJ', pasien_rj.AUD_PASIENRJ),
        url(r'^cekRMterakhir', pasien_rj.cekRMterakhir),
        url(r'^getDaftarPasien', pasien_rj.getDaftarPasien),
        url(r'^open_sumber', master_sumber.open_sumber),
    ])),
    url(r'^master_produk/', include ([
        url(r'^$',master_produk.master_produk, name='master_produk'),
        url(r'^getProdukHeader', master_produk.getProdukHeader),
        url(r'^getProdukDetail', master_produk.getProdukDetail),
        url(r'^getDatagol_klas', master_produk.getDatagol_klas),
        url(r'^getgol_klas', master_produk.getgol_klas),
        url(r'^get_klas_tarif', master_produk.get_klas_tarif),
        url(r'^get_produk_acc', master_produk.get_produk_acc),
        url(r'^get_produk_unit', master_produk.get_produk_unit),
        url(r'^save_produk_kelas', master_produk.save_produk_kelas),
        url(r'^getdataProduk_simpan', master_produk.getdataProduk_simpan),
        url(r'^getdataProduk', master_produk.getdataProduk),
        url(r'^tgl_produk_tarif',master_produk.tgl_produk_tarif),
        url(r'^get_produk_tarif',master_produk.get_produk_tarif),
        url(r'^save_produk_tarif',master_produk.save_produk_tarif),
    ])),
    url(r'^kasir_rj/', include ([
        url(r'^$',kasir_rj.kasir_rj, name='kasir_rj'),
        url(r'^getDaftarPasien', pasien_rj.getDaftarPasien),
        url(r'^getDataPasien', data_pasien.getDataPasien),
        url(r'^getReseler', data_pasien.getReseler),
        url(r'^getIdDataProduk', kasir_rj.getIdDataProduk),
        url(r'^getdataProduk', kasir_rj.getdataProduk),
        url(r'^getDiscCustomer', kasir_rj.getDiscCustomer),
        url(r'^getdokter', kasir_rj.getdokter),
        url(r'^getperawat', kasir_rj.getperawat),
        url(r'^getBC', kasir_rj.getBC),
        url(r'^getIdDokterProduk', kasir_rj.getIdDokterProduk),
        url(r'^SP_AUD_TRANSAKSI', kasir_rj.SP_AUD_TRANSAKSI),
        url(r'^getTransaksiByBukti', kasir_rj.getTransaksiByBukti),
        url(r'^getTransaksi', kasir_rj.getTransaksi),
        url(r'^cetakBilling', kasir_rj.cetakBilling),
        url(r'^getTpay', kasir_rj.getTpay),
        url(r'^getVoucherPay', kasir_rj.getVoucherPay),
        url(r'^SP_AUD_BAYAR_TRANSAKSI', kasir_rj.SP_AUD_BAYAR_TRANSAKSI),
        url(r'^findDepositPaketD', kasir_rj.findDepositPaketD),
        url(r'^findDepositPaket', kasir_rj.findDepositPaket),
        url(r'^getGridPaketprodukpasien',kasir_rj.getGridPaketprodukpasien),
        
    ])),
    url(r'^daftar_paket/', include ([
        url(r'^$',daftar_paket.daftar_paket, name='daftar_paket'),
        url(r'^getPasien', data_pasien.getPasien),
        url(r'^getDataPasien', data_pasien.getDataPasien),
        url(r'^getIdDataProduk', daftar_paket.getIdDataProduk),
        url(r'^getdataProduk', daftar_paket.getdataProduk),
        url(r'^getDiscCustomer', daftar_paket.getDiscCustomer),
        url(r'^getTransaksi', paket_produk.getTransaksi),
        url(r'^getpaketprodukByBukti', daftar_paket.getpaketprodukByBukti),
        url(r'^SP_AUD_DAFTAR_PAKET', daftar_paket.SP_AUD_DAFTAR_PAKET),
        url(r'^getDaftarPaketTransaksiByBukti', daftar_paket.getDaftarPaketTransaksiByBukti),
        url(r'^getDaftarPaketTransaksi', daftar_paket.getDaftarPaketTransaksi),
        url(r'^SP_AUD_BAYAR_TRANSAKSI', kasir_rj.SP_AUD_BAYAR_TRANSAKSI),
        url(r'^cetakBilling', daftar_paket.cetakBilling),
        
    ])),
    url(r'^paket_produk/', include ([
        url(r'^$',paket_produk.paket_produk, name='paket_produk'),
        url(r'^getIdDataProduk', daftar_paket.getIdDataProduk),
        url(r'^getdataProduk', daftar_paket.getdataProduk),
        url(r'^getDiscCustomer', daftar_paket.getDiscCustomer),
        url(r'^SP_AUD_PAKET', paket_produk.SP_AUD_PAKET),
        url(r'^getTransaksi', paket_produk.getTransaksi),
        url(r'^getpaketprodukByBukti', paket_produk.getpaketprodukByBukti),
    ])),
    url(r'^farmasi/', include ([
        url(r'^$',farmasi.farmasi, name='farmasi'),
        url(r'^getPasien', farmasi.getPasien),
        url(r'^getDataPasien', farmasi.getDataPasien),
        url(r'^getReseler', data_pasien.getReseler),
        url(r'^getDataDokter', farmasi.getDataDokter),
        url(r'^getdokter', farmasi.getdokter),
        url(r'^getDataGudang', farmasi.getDataGudang),
        url(r'^getgudang', farmasi.getgudang),
        url(r'^getIdDataBarang', farmasi.getIdDataBarang),
        url(r'^getDataBarang', farmasi.getDataBarang),
        url(r'^getDiscCustomer', farmasi.getDiscCustomer),
        url(r'^getParameter', farmasi.getParameter),
        url(r'^getHistoryBarang', farmasi.getHistoryBarang),
        url(r'^cekStokBarangFarmasi', farmasi.cekStokBarangFarmasi),
        url(r'^SP_AUD_FJINKOTA', farmasi.SP_AUD_FJINKOTA),
    ])),
    url(r'^jasamedis001/', include ([
        url(r'^$',jasamedis001.jasamedis001, name='jasamedis001'),
        url(r'^getdokter', kasir_rj.getdokter),
        url(r'^getperawat', kasir_rj.getperawat),
        url(r'^getBC', kasir_rj.getBC),
        url(r'^proses_excel', jasamedis001.proses_excel),
    ])),
    url(r'^jasareseller001/', include ([
        url(r'^$',jasareseller001.jasareseller001, name='jasareseller001'),
        url(r'^getReseler', data_pasien.getReseler),
        url(r'^proses_excel', jasareseller001.proses_excel),
    ])),
    url(r'^master_sumber/', include ([
        url(r'^$',master_sumber.master_sumber, name='master_sumber'),
        url(r'^open_sumber', master_sumber.open_sumber),
        url(r'^aud_Sumber', master_sumber.aud_Sumber),
        
 
    ])),
]
