from django.conf.urls import url
from django.urls import include, path
from . import frm_suplier
from . import frm_barang
from . import frm_pabrikan
from . import frm_jenis
from . import frm_produk
from . import frm_sediaan
from . import frm_lokasi
from . import frm_saldopersedian
from . import frm_order
from . import frm_beli
from . import modul_stock
from . import frm_mutasi_M
from . import frm_mutasi_K01
from . import frm_Ajdustment

urlpatterns = [
    url(r'^',include('farmasi.url_reportstock')),
    url(r'^frm_suplier/', include([
        url(r'^$', frm_suplier.frm_suplier, name='frm_suplier'),
        url(r'^exit', frm_suplier.exit, name='exitsuplier'),
        url(r'^load_barang', frm_barang.load_barang, name='load_barang'),
        url(r'^load_suplierDisc', frm_suplier.load_suplierDisc, name='load_suplierDisc'),
        url(r'^load_suplier', frm_suplier.load_suplier, name='load_suplier'),
        url(r'^suplier_simpan', frm_suplier.suplier_simpan, name='suplier_simpan'),
        url(r'^getsuplier', frm_suplier.getsuplier, name='getsuplier'),
        url(r'^getCoa2', frm_suplier.getCoa2, name='getCoa2'),
        url(r'^getcoa', frm_suplier.getcoa, name='getcoa'),
        url(r'^cetak_suplier', frm_suplier.cetak_suplier, name='cetak_suplier'),
        url(r'^getTpay', frm_suplier.getTpay, name='getTpay'),
        url(r'^barangdiscsup_simpan', frm_suplier.barangdiscsup_simpan, name='barangdiscsup_simpan'),
    ])),
    url(r'^frm_pabrikan/', include([
        url(r'^$', frm_pabrikan.frm_pabrikan, name='frm_pabrikan'),
        url(r'^exit', frm_pabrikan.exit, name='exitpabrikan'),
        url(r'^load_pabrikan', frm_pabrikan.load_pabrikan, name='load_pabrikan'),
        url(r'^pabrikan_simpan', frm_pabrikan.pabrikan_simpan, name='suplier_simpan'),
        url(r'^getpabrikan', frm_pabrikan.getpabrikan, name='getpabrikan'),
        url(r'^cetak_pabrikan', frm_pabrikan.cetak_pabrikan, name='cetak_pabrikan'),
    ])),
    url(r'^frm_jenis/', include([
        url(r'^$', frm_jenis.frm_jenis, name='frm_jenis'),
        url(r'^exit', frm_jenis.exit, name='exitjenis_barang'),
        url(r'^load_jenis_barang', frm_jenis.load_jenis_barang,name='load_jenis_barang'),
        url(r'^jenis_barang_simpan', frm_jenis.jenis_barang_simpan,name='jenis_barang_simpan'),
        url(r'^getjenis_barang', frm_jenis.getjenis_barang, name='getjenis_barang'),
        url(r'^cetak_jenis_barang', frm_jenis.cetak_jenis_barang,name='cetak_jenis_barang'),
    ])),
    url(r'^frm_produk/', include([
        url(r'^$', frm_produk.frm_produk, name='frm_produk'),
        url(r'^exit', frm_produk.exit, name='exitfrm_produk'),
        url(r'^load_produk_barang', frm_produk.load_produk_barang,name='load_produk_barang'),
        url(r'^produk_barang_simpan', frm_produk.produk_barang_simpan,name='produk_barang_simpan'),
        url(r'^getproduk_barang', frm_produk.getproduk_barang, name='getproduk_barang'),
        url(r'^cetak_produk_barang', frm_produk.cetak_produk_barang,name='cetak_produk_barang'),
    ])),
    url(r'^frm_sediaan/', include([
        url(r'^$', frm_sediaan.frm_sediaan, name='frm_sediaan'),
        url(r'^exit', frm_sediaan.exit, name='exitsediaan'),
        url(r'^load_sediaan', frm_sediaan.load_sediaan,name='load_sediaan'),
        url(r'^sediaan_simpan', frm_sediaan.sediaan_simpan,name='sediaan_simpan'),
        url(r'^getsediaan', frm_sediaan.getsediaan, name='getsediaan'),
        url(r'^cetak_sediaan', frm_sediaan.cetak_sediaan,name='cetak_sediaan'),
    ])),
    url(r'^frm_lokasi/', include([
        url(r'^$', frm_lokasi.frm_lokasi, name='frm_lokasi'),
        url(r'^exit', frm_lokasi.exit, name='exitlokasi'),
        url(r'^load_lokasi', frm_lokasi.load_lokasi,name='load_lokasi'),
        url(r'^lokasi_simpan', frm_lokasi.lokasi_simpan,name='lokasi_simpan'),
        url(r'^getlokasi', frm_lokasi.getlokasi, name='getlokasi'),
        url(r'^cetak_lokasi', frm_lokasi.cetak_lokasi,name='cetak_lokasi'),
    ])),
    url(r'^frm_barang/', include([
        url(r'^$', frm_barang.frm_barang, name='frm_barang'),
        url(r'^exit', frm_barang.exit, name='exitbarang'),
        url(r'^load_barang_stokmaxmin', frm_barang.load_barang_stokmaxmin, name='load_barang_stokmaxmin'),
        url(r'^load_barangNon', frm_barang.load_barangNon,name='load_barangNon'),
        url(r'^open_barang', frm_barang.open_barang,name='open_barang'),
        url(r'^load_barang', frm_barang.load_barang, name='load_barang'),
        url(r'^getgudang', frm_barang.getgudang,name='getgudang'),
        url(r'^getDatasuplier', frm_suplier.getDatasuplier, name='getDatasuplier'),
        url(r'^getjenis_barang', frm_jenis.getjenis_barang, name='getjenis_barang'),
        url(r'^getproduk_barang', frm_produk.getproduk_barang, name='getproduk_barang'),
        url(r'^getsediaan', frm_sediaan.getsediaan, name='getsediaan'),
        url(r'^getpabrikan', frm_pabrikan.getpabrikan, name='getpabrikan'),
        url(r'^getlokasi', frm_lokasi.getlokasi, name='getlokasi'),
        url(r'^getsuplier', frm_suplier.getsuplier, name='getsuplier'),
        url(r'^barang_simpan', frm_barang.barang_simpan, name='barang_simpan'),
        url(r'^barang_hapus', frm_barang.suplier_hapus, name='barang_hapus'),
        url(r'^cetak_barangwh', frm_barang.cetak_barangwh, name='cetak_barangwh'),
        url(r'^cetak_barang', frm_barang.cetak_barang, name='cetak_barang'),
        url(r'^barangwh_simpan', frm_barang.barangwh_simpan, name='barangwh_simpan'),
    ])),
    url(r'^frm_saldopersedian/', include([
        url(r'^$', frm_saldopersedian.frm_saldopersedian, name='frm_saldopersedian'),
        url(r'^exit', frm_saldopersedian.exit, name='exitfrm_saldopersedian'),
        url(r'^getgudang', frm_barang.getgudang,name='getgudang'),
        url(r'^getIdDataBarang', frm_saldopersedian.getIdDataBarang,name='getIdDataBarang'),
        url(r'^getDataBarang', frm_saldopersedian.getDataBarang,name='getDataBarang'),
        url(r'^getidsupplier', frm_saldopersedian.getidsupplier,name='getidsupplier'),
        url(r'^getsupplier', frm_saldopersedian.getsupplier,name='getsupplier'),
        url(r'^SP_AUD_SALDO', frm_saldopersedian.SP_AUD_SALDO, name='SP_AUD_SALDO'),
        url(r'^load_saldorekening', frm_saldopersedian.load_saldorekening, name='load_saldorekening'),
        url(r'^getsaldoByBukti', frm_saldopersedian.getsaldoByBukti, name='getsaldoByBukti'),
        url(r'^cetaksaldo', frm_saldopersedian.cetaksaldo, name='cetaksaldo'),
    ])),
    url(r'^frm_order/', include([
        url(r'^$', frm_order.frm_order, name='frm_order'),
        url(r'^exit', frm_order.exit, name='exitorder'),
        url(r'^getSupplier', frm_order.getSupplier, name='getSupplier'),
        url(r'^getTpay', frm_order.getTpay, name='getTpay'),
        url(r'^getIdDataBarang', frm_beli.getIdDataBarang, name='getIdDataBarang'),
        url(r'^getDataBarang', frm_order.getDataBarang, name='getDataBarang'),
        url(r'^getDataStatus', frm_order.getDataStatus, name='getDataStatus'),
        url(r'^getHistoryBarang', modul_stock.getHistoryBarang,name='getHistoryBarang'),
        url(r'^getHistoryBeliBarang', modul_stock.getHistoryBeliBarang,name='getHistoryBeliBarang'),
        url(r'^SP_AUD_ORDER', frm_order.SP_AUD_ORDER, name='SP_AUD_ORDER'),
        url(r'^getOrder_Pembelian', frm_order.getOrder_Pembelian,name='getOrder_Pembelian'),
        url(r'^getorderBarangByBuktiPembelian', frm_order.getorderBarangByBuktiPembelian,name='getorderBarangByBuktiPembelian'),
        url(r'^getSupPay', frm_order.getSupPay, name='getSupPay'),
        url(r'^getvalidasiOrder', frm_order.getvalidasiOrder,name='getvalidasiOrder'),
        url(r'^SPValidasiMutasi', frm_order.SPValidasiMutasi,name='SPValidasiMutasi'),
        url(r'^cetak_orderinternal', frm_order.cetak_orderinternal, name='cetak_orderinternal'),
        url(r'^cetak_order', frm_order.cetak_order, name='cetak_order'),
        url(r'^cetak_lap_rekap_supplier', frm_order.cetak_lap_rekap_supplier,name='cetak_lap_rekap_supplier'),
        url(r'^cetak_lap_rekap03', frm_order.cetak_lap_rekap03, name='cetak_lap_rekap03'),
        url(r'^cetak_lap_rekap02', frm_order.cetak_lap_rekap02, name='cetak_lap_rekap02'),
        url(r'^cetak_lap_rekap', frm_order.cetak_lap_rekap, name='cetak_lap_rekap'),
        url(r'^getDiscSuppBarang', frm_order.getDiscSuppBarang, name='getDiscSuppBarang'),
        url(r'^getcloseOrder', frm_order.getcloseOrder, name='getcloseOrder'),
        url(r'^SPcloseorder', frm_order.SPcloseorder, name='SPcloseorder'),
        url(r'^UNSPcloseorder', frm_order.UNSPcloseorder, name='UNSPcloseorder'),

    ])),
    url(r'^frm_beli/', include([
        url(r'^$', frm_beli.frm_beli, name='frm_beli'),
        url(r'^exit', frm_beli.exit, name='exitbeli'),
        url(r'^getSupplier', frm_beli.getSupplier, name='getSupplier'),
        url(r'^getPabrikan', frm_beli.getPabrikan, name='getPabrikan'),
        url(r'^getDataStatus', frm_order.getDataStatus, name='getDataStatus'),
        url(r'^getTpay', frm_beli.getTpay, name='getTpay'),
        url(r'^getDataGudang', frm_beli.getDataGudang),
        url(r'^getdivisi', frm_beli.getdivisi, name='getdivisi'),
        url(r'^getIdDataBarang', frm_beli.getIdDataBarang, name='getIdDataBarang'),
        url(r'^getDataBarang', frm_order.getDataBarang, name='getDataBarang'),
        url(r'^getPembelianByBuktiPembelian', frm_beli.getPembelianByBuktiPembelian,name='getPembelianByBuktiPembelian'),
        url(r'^getHistoryBeliBarang', modul_stock.getHistoryBeliBarang,name='getHistoryBeliBarang'),
        url(r'^SP_AUD_BELI', frm_beli.SP_AUD_BELI, name='SP_AUD_BELI'),
        url(r'^getPembelian', frm_beli.getPembelian, name='getPembelian'),
        url(r'^getBarangByBuktiPembelian', frm_beli.getBarangByBuktiPembelian,name='getBarangByBuktiPembelian'),
        url(r'^cetakPembelian', frm_beli.cetakPembelian, name='cetakPembelian'),
        url(r'^getOrder_Pembelian', frm_beli.getOrder_Pembelian,name='getOrder_Pembelian'),
        url(r'^getorderBarangByBuktiPembelian', frm_beli.getorderBarangByBuktiPembelian,name='getorderBarangByBuktiPembelian'),
        url(r'^getvalidasiPembelian', frm_beli.getvalidasiPembelian,name='getvalidasiPembelian'),
        url(r'^SPValidasiMutasi', frm_beli.SPValidasiMutasi,name='SPValidasiMutasi'),
        url(r'^UNSPValidasiMutasi', frm_beli.UNSPValidasiMutasi,name='UNSPValidasiMutasi'),
        url(r'^SPPerubahanfaktur', frm_beli.SPPerubahanfaktur,name='SPPerubahanfaktur'),
        url(r'^cetak_lap_rekap_supplier', frm_beli.cetak_lap_rekap_supplier,name='cetak_lap_rekap_supplier'),
        url(r'^cetak_lap_rekap', frm_beli.cetak_lap_rekap, name='cetak_lap_rekap'),
        url(r'^cetak_supp_pabrik_gudang', frm_beli.cetak_supp_pabrik_gudang, name='cetak_supp_pabrik_gudang'),
        url(r'^cetak_lap_Pembelian', frm_beli.cetak_lap_Pembelian, name='cetak_lap_Pembelian'),
    ])),
    url(r'^frm_mutasi_M/', include([
        url(r'^$', frm_mutasi_M.frm_mutasi_M, name='frm_mutasi_M'),
        url(r'^exit', frm_mutasi_M.exit, name='exitfrm_mutasi_M'),
        url(r'^getSupplier', frm_mutasi_M.getSupplier, name='getSupplier'),
        url(r'^getdivisi', frm_mutasi_M.getdivisi, name='getdivisi'),
        url(r'^getDataGudang', frm_beli.getDataGudang, name='getDataGudang'),
        url(r'^getDataStatus', frm_order.getDataStatus, name='getDataStatus'),
        url(r'^getIdDataBarang', frm_beli.getIdDataBarang, name='getIdDataBarang'),
        url(r'^getDataBarangKeluar', modul_stock.getDataBarangKeluar,name='getDataBarangKeluar'),
        url(r'^getHistoryBarang', modul_stock.getHistoryBarang,name='getHistoryBarang'),
        url(r'^SP_AUD_CLAIMS', frm_mutasi_M.SP_AUD_CLAIMS, name='SP_AUD_CLAIMS'),
        url(r'^getMutasiMasuk', frm_mutasi_M.getMutasiMasuk, name='getMutasiMasuk'),
        url(r'^getBarangByBukti', frm_mutasi_M.getBarangByBukti,name='getBarangByBukti'),
        url(r'^cetakBarang', frm_mutasi_M.cetakBarang, name='cetakBarang'),
        url(r'^cetak_lap_rekap_divisi', frm_mutasi_M.cetak_lap_rekap_divisi,name='cetak_lap_rekap_divisi'),

    ])),

    url(r'^frm_mutasi_K01/', include([
        url(r'^$', frm_mutasi_K01.frm_mutasi_K01, name='frm_mutasi_K01'),
        url(r'^exit', frm_mutasi_K01.exit, name='exitfrm_mutasi_K01'),
        url(r'^getDataGudang', frm_beli.getDataGudang, name='getDataGudang'),
        url(r'^getdivisi', frm_mutasi_K01.getdivisi, name='getdivisi'),
        url(r'^getIdDataBarang', frm_mutasi_K01.getIdDataBarang, name='getIdDataBarang'),
        url(r'^getDataBarangKeluar', modul_stock.getDataBarangKeluar,name='getDataBarangKeluar'),
        url(r'^getHistoryBarang', modul_stock.getHistoryBarang,name='getHistoryBarang'),
        url(r'^cekStokBarangFarmasi', modul_stock.cekStokBarangFarmasi, name='cekStokBarangFarmasi'),
        url(r'^SP_AUD_PCLAIMS', frm_mutasi_K01.SP_AUD_PCLAIMS, name='SP_AUD_PCLAIMS'),
        url(r'^getMutasiKeluar', frm_mutasi_K01.getMutasiKeluar,name='getMutasiKeluar'),
        url(r'^getBarangByBuktiKeluar', frm_mutasi_K01.getBarangByBuktiKeluar, name='getBarangByBuktiKeluar'),
        url(r'^cetakBarangKeluar', frm_mutasi_K01.cetakBarangKeluar,name='cetakBarangKeluar'),
        url(r'^cetak_lap_mutasi_BHP_REKAP', frm_mutasi_K01.cetak_lap_mutasi_BHP_REKAP, name='cetak_lap_mutasi_BHP_REKAP'),
        url(r'^cetak_lap_mutasi_BHP', frm_mutasi_K01.cetak_lap_mutasi_BHP, name='cetak_lap_mutasi_BHP'),
    ])),

    url(r'^frm_Ajdustment/', include([
        url(r'^$', frm_Ajdustment.frm_Ajdustment, name='frm_Ajdustment'),
        url(r'^exit', frm_Ajdustment.exit, name='exitfrm_Ajdustment'),
        url(r'^getDataGudang', frm_beli.getDataGudang, name='getDataGudang'),
        url(r'^getdivisi', frm_Ajdustment.getdivisi, name='getdivisi'),
        url(r'^getIdDataBarang', frm_Ajdustment.getIdDataBarang, name='getIdDataBarang'),
        url(r'^getDataBarangKeluar', modul_stock.getDataBarangKeluar,name='getDataBarangKeluar'),
        url(r'^getHistoryBarang', modul_stock.getHistoryBarang,name='getHistoryBarang'),
        url(r'^cekStokBarangFarmasi', modul_stock.cekStokBarangFarmasi, name='cekStokBarangFarmasi'),
        url(r'^SP_AUD_PCLAIMS', frm_Ajdustment.SP_AUD_PCLAIMS, name='SP_AUD_PCLAIMS'),
        url(r'^getMutasiKeluar', frm_Ajdustment.getMutasiKeluar,name='getMutasiKeluar'),
        url(r'^getBarangByBuktiKeluar', frm_Ajdustment.getBarangByBuktiKeluar,name='getBarangByBuktiKeluar'),
        url(r'^cetakBarangKeluar', frm_Ajdustment.cetakBarangKeluar, name='cetakBarangKeluar'),
        url(r'^cetak_lap_mutasi_BHP_REKAP', frm_Ajdustment.cetak_lap_mutasi_BHP_REKAP,name='cetak_lap_mutasi_BHP_REKAP'),
        url(r'^cetak_lap_mutasi_BHP', frm_Ajdustment.cetak_lap_mutasi_BHP,name='cetak_lap_mutasi_BHP'),
        
    ])),




]